export const SITES_REQUEST = 'SITES_REQUEST';
export const SITES_REQUEST_FAILURE = 'SITES_REQUEST_FAILURE';
export const SITES_REQUEST_SUCCESS = 'SITES_REQUEST_SUCCESS';
export const SITES_RECEIVE = 'SITES_RECEIVE';
export const SERIALIZE = 'SERIALIZE';
export const DESERIALIZE = 'DESERIALIZE';
